### ISSUE TITLE
Seed Guard Crashes When Rejoining a World

### ISSUE THREAD

**Issue by cntrik** [DrexHD/SeedGuard#1]
Minecraft 1.20.1
Fabric Loader 0.14.22

Steps:
Load into a World
Exit
Reload into same World
Crashes
https://gist.github.com/Afrocntrik/ca642ce39f4b96abdf6c38bf6688a43e

**Comment by DrexHD** [comment]
This is a weird issue. I am able to reproduce it, but I currently have no clue what's causing it (I am not super familiar with the exact behavior of the Integrated Server in singleplayer). The mod is mainly intended to be used on servers and has only been tested on dedicated servers before release. May I ask why you want to use it in singleplayer?

**Comment by cntrik** [comment]
@DrexHD Currently working on a modpack rn now it's a bit cursed in the modlist but I believe it will be uniquely fun. SeedGuard is there to allow structures to still spawn and offset the Random Chunks mod I have installed. Best guess would be the mod is trying to modify structure placement or seed it gets them from on rejoining the world
