### ISSUE TITLE
[Suggestion/Request] Specify the seeds used for features/structures

### ISSUE THREAD

**Issue by HatTrkPatrk** [DrexHD/SeedGuard#2]
I wanted to suggest a feature/change. Vanilla uses a hardcoded seed, and this mod randomizes the seed instead. Could this mod provide an optional config that lets you specify what seeds to use for those, instead of randomizing them?

**Comment by DrexHD** [comment]
The mod needs to ensure seeds are kept consistent throughout reboots, so it saves and loads the seed values from `world/feature-seeds.json` and `world/structure-seeds.json`. If you want to manually specify the seeds, you can generate these files and use them in another world, with your adjusted values.
